/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MESSAGEPROG 0x20083001
#define MESSAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define APPEND 2
extern  int * append_1(char **, CLIENT *);
extern  int * append_1_svc(char **, struct svc_req *);
#define DELETE 3
extern  int * delete_1(char **, CLIENT *);
extern  int * delete_1_svc(char **, struct svc_req *);
#define REMOVE 4
extern  int * remove_1(char **, CLIENT *);
extern  int * remove_1_svc(char **, struct svc_req *);
#define COUNT 5
extern  int * count_1(char **, CLIENT *);
extern  int * count_1_svc(char **, struct svc_req *);
#define FIND 6
extern  char ** find_1(int *, CLIENT *);
extern  char ** find_1_svc(int *, struct svc_req *);
#define SEARCH 7
extern  char ** search_1(char **, CLIENT *);
extern  char ** search_1_svc(char **, struct svc_req *);
extern int messageprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define APPEND 2
extern  int * append_1();
extern  int * append_1_svc();
#define DELETE 3
extern  int * delete_1();
extern  int * delete_1_svc();
#define REMOVE 4
extern  int * remove_1();
extern  int * remove_1_svc();
#define COUNT 5
extern  int * count_1();
extern  int * count_1_svc();
#define FIND 6
extern  char ** find_1();
extern  char ** find_1_svc();
#define SEARCH 7
extern  char ** search_1();
extern  char ** search_1_svc();
extern int messageprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
