/*
 * msg_proc.c: implementation of the remote procedure "printmessage"
 *
 * Source: ?Using rpcgen?, http://www.cisco.com/en/US/docs/ios/sw_upgrades/interlink/r2_0/rpc_pr/rprpcgen.html
 */

#include <stdio.h>
#include <stdlib.h>
#include <rpc/rpc.h>	/* always needed */
#include "msg.h"	/* need this too: msg.h will be generated by rpcgen */

/*
 * Remote verson of "printmessage"
 */

int append_l = 7;
int count_l = 6;
int find_l = 5;
char divider = '\n';

//todo: 
	//return strings
	//first word
	//partial matches
int get_next_sentence(FILE *f, char *sen) {
	if (f==NULL) return -1;
	fscanf(f, "%100c", sen);
	for (int i = 0; i<100; i++) {
		if (*(sen+i)=='\n') {
			*(sen+i+1) = '\0';
			return i;
		}
	}
	return -1;
}

int *append_1_svc (char **msg, struct svc_req *rqstp) {
	static int result; /* must be static! */
	FILE *f;

	f = fopen("output.txt", "a");// opens output file 
	if (f == NULL) 
	{
		result = 0;
		return (&result);
	}
	char s[100];
	char *m = s;
	strncpy(m, *msg+append_l, strlen(*msg)-append_l-1);
	s[strlen(*msg)-append_l-1] = '\0';
	fprintf(f, "%s\n", m);//writes message
	fclose(f);

	result = 1; //success
	return (&result);
}

int *delete_1_svc (char **msg, struct svc_req *rqstp) {
	static int result; /* must be static! */
	FILE *f;
	f = fopen("output.txt", "r");
	if (f == NULL) 
	{
		result = 0;
		return (&result);
	}
	char s[100]; //get rid of word and brackets - should be a function
	char *m = s;
	strncpy(m, *msg+append_l, strlen(*msg)-append_l-1);
	s[strlen(*msg)-append_l-1] = '\0';

	fseek(f, 0, SEEK_END);
	int l = ftell(f); //total length of the file
	fseek(f,-l,SEEK_END);

	char new[l], temp[100], temp2[100];
	int j = 0;
	for (int i = 0; i<l; i++) {
		fseek(f, i, SEEK_SET);
		i = i+get_next_sentence(f,temp);
		char *w;
		if (i<l) {
		while (w = strstr(temp,m)) {
			strcpy(temp2, w+strlen(m)+1);
			strcpy(w, temp2);
		}
		strcpy(new+j,temp);
		j = j+strlen(temp);}
			
	}
	fclose(f);
	f = fopen("output.txt", "w");
	fprintf(f, "%s", new);
	fclose(f);
	result = 1;
	return &result;
}

int *find_1_svc (char **msg, struct svc_req *rqstp) {
	static int result;
	FILE *f;
	f = fopen("output.txt", "r");// opens output file 
	if (f == NULL) 
	{
		result = 0;
		return (&result);
	}
	
	int x;
	char s[100]; //get rid of word and brackets
	char *m = s;
	strncpy(m, *msg+find_l, strlen(*msg)-find_l-1);

	s[strlen(*msg)] = '\0';
	x = atoi(m);
	int l = 0;
	char temp[100];
	for (int i = 0; i<x; i++) {
		l = l+get_next_sentence(f, temp)+1;
		fseek(f, l, SEEK_SET);
	}
	*(*msg) = *temp;
	result = 1;
	return &result;

}

int *remove_1_svc (char **msg, struct svc_req *rqstp){
	static int result; /* must be static! */
	FILE *f;
	f = fopen("output.txt", "r");
	if (f == NULL) 
	{
		result = 0;
		return (&result);
	}
	char s[100]; //get rid of word and brackets - should be a function
	char *m = s;
	strncpy(m, *msg+append_l, strlen(*msg)-append_l-1);
	s[strlen(*msg)-append_l-1] = '\0';

	fseek(f, 0, SEEK_END);
	int l = ftell(f); //total length of the file
	fseek(f,-l,SEEK_END);

	char new[l], temp[100], temp2[100];
	int j = 0;
	for (int i = 0; i<l; i++) {
		fseek(f, i, SEEK_SET);
		i = i+get_next_sentence(f,temp);
		temp[strlen(temp)-1] = '\0';
		char *w;
		if (i<l) {
		printf("comparison:\n%s\n%s\n%d\n", temp, m, strcmp(temp,m));
		if (strcmp(temp,m)) {
			temp[strlen(temp)-1] = '\n';
			strcpy(new+j,temp);
			j = j+strlen(temp);
		}
		}
			
	}
	fclose(f);
	f = fopen("output.txt", "w");
	fprintf(f, "%s", new);
	fclose(f);
	result = 1;
	return &result;
}

int *old_remove (char **msg, struct svc_req *rqstp){
	static int result; /* must be static! */
	FILE *f;

	char s[100]; //get rid of word and brackets
	char *m = s;
	strncpy(m, *msg+append_l, (strlen(*msg)-append_l-1));
	s[strlen(*msg)-append_l-1] = '\0';



	f = fopen("output.txt", "r");// opens output file 
	if (f == NULL) 
	{
		result = 0;
		return (&result);
	}
	fseek(f,0, SEEK_END);
	int l = ftell(f);
	fseek(f,-l,SEEK_END);
	
	char t[l];
	char * temp = t;
	char * format;
	
	sprintf(format, "%c%d%c\0", '%', l, 'c');
	fscanf(f, format, temp);
	fclose(f);
	char t2[l];
	char * temp2 = t2;
	char *x = temp;
	while (temp = strstr(temp,m)){
		printf("\n\n\n\n\n\n%s \n %s  %d\n", temp+strlen(m)+1, temp2, strlen(m));
		strcpy (temp2, temp);
		strcpy(temp, temp2+strlen(m)+1);
		//printf("%s\n", temp);
		temp = temp+strlen(m)+1;
		
	}
	fopen("output.txt", "w");
	if (f ==NULL) {
		result = 0;
		return &result;
	}
	fprintf(f, "%s\n", x);
	fclose(f);
	result = 1;
	return (&result);
}

int *search_1_svc (char **msg, struct svc_req *rqstp){
	static int result; /* must be static! */
	FILE *f;
	f = fopen("output.txt", "r");
	if (f == NULL) 
	{
		result = 0;
		return (&result);
	}
	char s[100]; //get rid of word and brackets - should be a function
	char *m = s;
	strncpy(m, *msg+append_l, strlen(*msg)-append_l-1);
	s[strlen(*msg)-append_l-1] = '\0';

	fseek(f, 0, SEEK_END);
	int l = ftell(f); //total length of the file
	fseek(f,-l,SEEK_END);

	char new[l], temp[100], temp2[100];
	int j = 0;
	for (int i = 0; i<l; i++) {
		fseek(f, i, SEEK_SET);
		i = i+get_next_sentence(f,temp);

		char *w;
		if (i<l) {
		if (w = strstr(temp,m)) {
			printf("found it\n%s", temp);
			result = 1;
			return &result;
		}
		strcpy(new+j,temp);
		j = j+strlen(temp);}
			
	}
	fclose(f);
	result = 1;
	return &result;
}

int *count_1_svc (char **msg, struct svc_req *rqstp) { //fix for first being the thing you want

	static int result; /* must be static! */
	FILE *f;

	char s[100]; //get rid of word and brackets
	char *m = s;
	strncpy(m, *msg+count_l, strlen(*msg)-count_l-1);
	s[strlen(*msg)-count_l-1] = '\0';
	f = fopen("output.txt", "r");// opens output file 
	if (f == NULL) 
	{
		result = 0;
		return (&result);
	}
	fseek(f,0, SEEK_END);
	int l = ftell(f);
	fseek(f,-l,SEEK_END);
	int count = 0;
	char t[l];
	char * temp = t;
	char * format;
	sprintf(format, "%c%d%c\0", '%', l, 'c');
	fscanf(f, format, temp);
	while (temp = strstr(temp+strlen(m),m)){
		count++;
	}

	fclose(f);

	result = count;
	return (&result);
}
